### ISSUE TITLE
Missing textures and Bedrock Ore descriptions returning nothing despite data being present (Lang error fixed but details are not)

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#309]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/91ff8d47-ef19-4fab-a069-9addf5b75867)
seems like the fixing of the bedrock stuff lead to some things being forgotten

![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/47e33257-8b74-492b-8d2c-ce8071caa567)
Now this one appears to be the result of some other fixes; to note wearing the masks normaly appears to have the same issue that was corrected when seaking wtih some of the armors that were fixed; at least the attachment for the gas mask is now synced up when sneaking

**Comment by Shibva** [comment]
Further Elaboration: 
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/1d36d886-5672-4d77-b94d-aec5dd54117a)
seems like most of the things were fixed but a few outliers were probally forgotten

**Comment by TheSlize** [comment]
Bedrock ore translate fixed (fully in the next upcoming commit)

**Comment by Shibva** [comment]
To compile the issues into one thing:

- Bedrock appears to be fixed; but lang entries got scuffed (confimed to be fixed in next update afaik)
- Mask attachments and armors now sync up when seaking; but it appears the texture for the attachment broke
- Original Gas masks appear to have been an unknown thing affiliated with the sneaking armor bug causing their rendering to break; this bug having been fixed means that it was likely these were unknown to be affected as well

**Comment by Shibva** [comment]
I have found a few other bugs Ill make a seperate report for but need further testing; aside from that these are the only issues the new release I have been able to find atm

**Comment by Shibva** [comment]
I saw that in an hotfix but it appears that the lang is somewhat still broken

**Comment by Shibva** [comment]
To Clarify what I mean in the above comment:
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/939dfe31-2e39-403b-8f48-46cd233a3844)
(lang is fixed... though what is ment to display is not)

it also is not null, Using Craftweakers `/ct blockinfo` utility; I got a return with data so its just the display portion is busted from the overall changes made to the bedrock ore
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/0fff958d-0529-43ce-85e1-35355a5a7556)

(also as of lattest, Coltain Bedrock ore is removed but if you are going to apply this, maybe have some method to replace the block so there are no holes in the floor lelelelel)


Another few things; The SuperShotgun is unfinished (from what drill had envisioned) but for the most part is fuctional; it is however missing a model texture; if its gonna be implemented as a recipe its probs best to attach the texture onto it

Lastly, a "Joke" Drill made but forgot to change out and has been stuck in the mod for some time is the Thompson Submachine Gun model being.... a cat
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/636319fd-5e6d-4361-baba-546869537049)
IMO if its possible Id say you can keep this as some easter egg by naming the gun something... idk

**Comment by TheSlize** [comment]
> To Clarify what I mean in the above comment:

Strange, cuz I don't have this issue (only tier was somehow missing but I fixed it, will be with the next commited translation chunk from me)

> Lastly, a "Joke" Drill made but forgot to change out and has been stuck in the mod for some time is the Thompson Submachine Gun model being.... a cat

I guess that IS an easter egg, afar it has been at least for a year (and in reloaded as well)

**Comment by Shibva** [comment]
it was in for some time; I was testing stuff in the original port before it changed hands and got forked; I talked wtih Drill about it and said it was some fun thing; guess it never got fully implemented and got trapped in this Limbo state of being not fully implemented as a full-on easter egg; I think the original texture might still exist somewhere if you go digging in the original ports commits

**Comment by Shibva** [comment]
> Strange, cuz I don't have this issue (only tier was somehow missing but I fixed it, will be with the next commited translation chunk from me)

Wonder if its because its in an existing world or something; but even then I placed a new one and it still acted up

EDIT: Nope, still occured on a completely new world; I will say though Im using a config that now that I think about it question if its syntax had altered

**Comment by Shibva** [comment]
I wonder if it has something todo wiht the config that was generated before the fix wtih bedrock ores

[hbm_bedrock_ores.json](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/14234148/hbm_bedrock_ores.json)
heres my config just in case; I noticed some of the acutal HBM config regenerated (shaders2 which I had on for the flashlight stuff got turned off when I had it on and futher investigating lead me to that)

**Comment by Shibva** [comment]
Decided to test it a bit further and eveything else is working correctly asside from the vein display stuff; getting ore from it still so its not a syntax issue except for maybe some fuckup in the display code

**Comment by Shibva** [comment]
... and I ran into a nother bug by shear chance XD
seems like if the inventory is full the drill wont stop atempting to mine; or at the very lest prevent it from consuming the fluid used to extract from the deposit
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/a1f5a933-1138-444a-80f0-363dc8d0cc6c)

ill be lableing this under a seperate bug

**Comment by Shibva** [comment]
It seems that this have gotten a bit cluttered; I'll be making separate reports on each individual thing that needs to be addressed and closing this as incomplete

**Comment by Shibva** [comment]
with a report made on the only issue remaining minus the gatto gun; I will close this one in favor of the other with the issue with bedrock having been hopefully adressed
