### ISSUE TITLE
Galacticraft's oil bucket behaves strangely in the fluid tank

### ISSUE THREAD

**Issue by eterraria** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#47]
When I put the oil bucket added by Galacticraft ("galacticraftcore:bucket_oil") into any type of fluid tank, the bucket will never empty while outputing oil continuously like the infinite water bucket. Other fluid buckets added by Galacticraft also have similar problems.

Mod version: 1.12.2-1.8.4c
Galacticraft version:1.12.2-4.0.3

**Comment by KaxelOleg** [comment]
> When I put the oil bucket added by Galacticraft ("galacticraftcore:bucket_oil") into any type of fluid tank, the bucket will never empty while outputing oil continuously like the infinite water bucket. Other fluid buckets added by Galacticraft also have similar problems.
> 
> Mod version: 1.12.2-1.8.4c Galacticraft version:1.12.2-4.0.3

I fixed it.

**Comment by eterraria** [comment]
> I fixed it.

This problem still exists in the latest version (1.9.0).
Could you tell me how to deal with the problem in detail?
